name: Prettier Format JSON

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Prettier
        run: npm install prettier

      - name: Get all changed json locale files
        id: changed-json-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **.json

      - name: Format JSON files with Prettier
        if: steps.changed-json-files.outputs.any_changed == 'true'
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
            npx prettier --write --tab-width 4 $file
          done

      - name: Commit changes
        run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add .
            git commit -m "chore: auto-format JSON with Prettier"
            git push
          fi
